config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :movies
  resources :lists do
    resources :bookmarks, only: [:new, :create, :update, :destroy, :show]
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message:"The movie is in the list already" }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  # validates :poster_url, presence: true
  # validates :rating, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      puts @bookmark.errors.full_messages
      render :new, status: :unprocessable_entity
    end
     rescue => e
      puts "❌ ERROR: #{e.class.name} - #{e.message}"
      puts e.backtrace.take(10)  # just top of stack
      render plain: "An error occurred: #{e.message}", status: :internal_server_error

  end

   def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_bookmark_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
     params.require(:bookmark).permit(:comment, :movie_id )
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

 def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController


  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.find(movie_params)
    if @movie.save
      redirect_to movie_path(@movie)
    else
      render :new, status: :unprocessable_entity
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="p-3">
<h1>Create a bookmark</h1>

<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
    <%= f.association :movie, collection: Movie.all, prompt: "Select a movie" %>
  <%= f.button :submit %>
<% end %>



 <%= link_to "Back to lists", lists_path%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="p-3 text-decoration-none">
<h1>Lists</h1>
<div class="mt-4 border-bottom border-secondary-subtle border-2 mb-4 text-decoration-none">
<ul class="list-inline">
  <% @lists.each do |list| %>
     <li class="mb-5">
     <h2><%= list.name %></h2>
     <%= link_to "See this list", list_path(list) %>

     </li>
  <% end %>

  <%= link_to "Create a list", new_list_path %> |
  <%= link_to "See all movies", movies_path %>

app/views/lists/new.html.erb
<div class="p-3">
<h1>New List</h1>
<%= simple_form_for(@list) do |f| %>
<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
</div>
<div class="form-actions btn btn-primary mb-4">
  <%= f.button :submit %>
</div>
<% end %>
 <%= link_to "Back to lists", lists_path%>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key %>');">
  <div class="container">
    <h1><%= @list.name %></h1>
    <p>Watch some great movies.</p>
  </div>
</div>

<div class="p-3 text-decoration-none">
<div class="mt-4 border-bottom border-secondary-subtle border-2 mb-4 text-decoration-none">
<ul class="list-inline">
  <% @bookmarks.each do |bookmark| %>
     <li class="mb-5">
     <h2><%= bookmark.movie.title %></h2>
     <p><%= bookmark.movie.overview %></p>
     <img src="<%= bookmark.movie.poster_url %>" alt="image not found" class="img-thumbnail img-fluid" width=200 >
     <p><%= bookmark.comment %></p>
     <h5><%= bookmark.movie.rating %> ⭐️</h5>
     <%= link_to "Delete", list_bookmark_path(@list, bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure" } %>
     </li>
  <% end %>
</ul>
</div>
</div>


<div>
    <%= link_to "Create a bookmark", new_list_bookmark_path(@list) %>
    <%= link_to "Back to lists", lists_path %>
</div>

app/views/movies/index.html.erb
<div class="p-3 text-decoration-none">
<h1>Movies</h1>
<div class="mt-4 border-bottom border-secondary-subtle border-2 mb-4 text-decoration-none">
<ul class="list-inline">
  <% @movies.each do |movie| %>
     <li class="mb-5">
     <h2><%= movie.title %></h2>
     <p><%= movie.overview %></p>
     <img src="<%= movie.poster_url %>" alt="image not found" class="img-thumbnail img-fluid" width=200 >
     <h5><%= movie.rating %> ⭐️</h5>
     </li>
  <% end %>
</ul>

  <%= link_to "Back to lists", lists_path %>